export { ProductController } from "./controller/index.js";
export { PRODUCT_TYPES } from "./constants/index.js";
export type { ProductType } from "./constants/index.js";
export type { CreateProductDto, UpdateProductDto } from "./dto/index.js";
export { ProductModel } from "./model/index.js";
export type { ComboItem, Product } from "./model/index.js";
export { ProductRepository } from "./repository/index.js";
export { productRouter } from "./routes/index.js";
export { ProductService } from "./service/index.js";
export type { ProductResponse } from "./types/index.js";
