export const APP_ERROR_CODES = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  CORS_ORIGIN_NOT_ALLOWED: "CORS_ORIGIN_NOT_ALLOWED",
  DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
  OTP_COOLDOWN_ACTIVE: "OTP_COOLDOWN_ACTIVE",
  OTP_RESEND_LIMIT_REACHED: "OTP_RESEND_LIMIT_REACHED",
  OTP_INVALID_OR_EXPIRED: "OTP_INVALID_OR_EXPIRED",
  OTP_ATTEMPTS_EXCEEDED: "OTP_ATTEMPTS_EXCEEDED",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  USER_BLOCKED: "USER_BLOCKED",
} as const;

export type AppErrorCode =
  (typeof APP_ERROR_CODES)[keyof typeof APP_ERROR_CODES];
