export const ROUTES = {
  ADDRESS: "/addresses",
  AUTH: "/auth",
  CART: "/cart",
  CHECKOUT: "/checkout",
  CATEGORY: "/categories",
  FAVORITE: "/favorites",
  HEALTH: "/health",
  MEDIA: "/media",
  NOTIFICATION: "/notifications",
  OCCASION: "/occasions",
  ORDER: "/orders",
  PAYMENT: "/payments",
  PLATFORM: "/platform",
  PRODUCT: "/products",
  REVIEW: "/reviews",
  SEARCH: "/search",
  SETTINGS: "/settings",
  UPLOAD: "/upload",
  USER: "/users",
  VILLAGE: "/villages",
  COUPONS: "/coupons",
  BRANCH: "/branches",
  DELIVERY_AGENT: "/delivery-agent",
  CUSTOM_CAKE: "/custom-cake",
  COMBOS: "/combos",
  BANNER: "/banners",
  DECORATIONS: "/decorations",
} as const;

